api_params:
  /api/trantor/service/engine/execute/SCM_REB$SYS_FindSingleDataByConditionService:
    params:
      selectFields:
      - selectFields:
        - {}
        field: null
      request:
        conditionItems: null
        conditionGroup: null
      modelKey: null
    serviceKey: SCM_REB$SYS_FindSingleDataByConditionService
  /api/trantor/service/engine/execute/SCM_REB$SYS_FindDataByIdService:
    params:
      selectFields:
      - selectFields:
        - {}
        field: null
      request:
        id: 0
      modelKey: null
    serviceKey: SCM_REB$SYS_FindDataByIdService
  /api/trantor/service/engine/execute/SCM_REB$SYS_FindTreeChildrenDataService:
    params:
      request:
        conditionItems: null
        conditionGroup: null
      modelKey: null
    serviceKey: SCM_REB$SYS_FindTreeChildrenDataService
  /api/trantor/service/engine/execute/SCM_REB$SYS_MasterData_DisableDataService:
    params:
      request:
        id: 0
      modelKey: null
    serviceKey: SCM_REB$SYS_MasterData_DisableDataService
  /api/trantor/service/engine/execute/SCM_REB$SYS_FindOneDataService:
    params:
      selectFields:
      - selectFields:
        - {}
        field: null
      request:
        conditionItems: null
        conditionGroup: null
      modelKey: null
    serviceKey: SCM_REB$SYS_FindOneDataService
  /api/trantor/service/engine/execute/SCM_REB$SYS_InvokeCodeRuleService:
    params:
      request:
        formParams: {}
        ruleKey: null
      modelKey: null
    serviceKey: SCM_REB$SYS_InvokeCodeRuleService
  /api/trantor/service/engine/execute/SCM_REB$SYS_DeleteDataByIdService:
    params:
      request:
        id: 0
      modelKey: null
    serviceKey: SCM_REB$SYS_DeleteDataByIdService
  /api/trantor/service/engine/execute/SCM_REB$SYS_MasterData_MultiEnableDataService:
    params:
      request:
        ids:
        - 0
      modelKey: null
    serviceKey: SCM_REB$SYS_MasterData_MultiEnableDataService
  /api/trantor/service/engine/execute/SCM_REB$SYS_MasterData_MultiDisableDataService:
    params:
      request:
        ids:
        - 0
      modelKey: null
    serviceKey: SCM_REB$SYS_MasterData_MultiDisableDataService
  /api/trantor/service/engine/execute/SCM_REB$SYS_SUM_DATA_SERVICE:
    params:
      request:
        conditionItems: null
        conditionGroup: null
      fields:
      - null
      modelKey: null
    serviceKey: SCM_REB$SYS_SUM_DATA_SERVICE
  /api/trantor/service/engine/execute/SCM_REB$SYS_MasterData_EnableDataService:
    params:
      request:
        id: 0
      modelKey: null
    serviceKey: SCM_REB$SYS_MasterData_EnableDataService
  /api/trantor/service/engine/execute/SCM_REB$SYS_MasterData_SaveAndEnableDataService:
    params:
      request: {}
      modelKey: null
    serviceKey: SCM_REB$SYS_MasterData_SaveAndEnableDataService
  /api/trantor/service/engine/execute/SCM_REB$SYS_BatchDeleteDataByConditionService:
    params:
      request:
        conditionItems: null
        conditionGroup: null
      modelKey: null
    serviceKey: SCM_REB$SYS_BatchDeleteDataByConditionService
  /api/trantor/service/engine/execute/SCM_REB$SYS_BatchUpdateDataByConditionService:
    params:
      request:
        data: {}
        conditionItems: null
        conditionGroup: null
      modelKey: null
    serviceKey: SCM_REB$SYS_BatchUpdateDataByConditionService
  /api/trantor/service/engine/execute/SCM_REB$SYS_MasterData_CreateAndEnableDataService:
    params:
      request: {}
      modelKey: null
    serviceKey: SCM_REB$SYS_MasterData_CreateAndEnableDataService
  /api/trantor/service/engine/execute/SCM_REB$SYS_FindListDataService:
    params:
      selectFields:
      - selectFields:
        - {}
        field: null
      request:
        conditionItems: null
        conditionGroup: null
      modelKey: null
    serviceKey: SCM_REB$SYS_FindListDataService
  /api/trantor/service/engine/execute/SCM_REB$SYS_ReverseConstructTreeService:
    params:
      request:
        conditionItems: null
        conditionGroup: null
      modelKey: null
    serviceKey: SCM_REB$SYS_ReverseConstructTreeService
  /api/trantor/service/engine/execute/SCM_REB$SYS_UpdateDataByIdService:
    params:
      request: {}
      modelKey: null
    serviceKey: SCM_REB$SYS_UpdateDataByIdService
  /api/trantor/service/engine/execute/SCM_REB$SYS_FindSingleDataByIdService:
    params:
      selectFields:
      - selectFields:
        - {}
        field: null
      request:
        id: 0
      modelKey: null
    serviceKey: SCM_REB$SYS_FindSingleDataByIdService
  /api/trantor/service/engine/execute/SCM_REB$SYS_BatchUpdateDataByIdsService:
    params:
      request:
      - {}
      modelKey: null
    serviceKey: SCM_REB$SYS_BatchUpdateDataByIdsService
  /api/trantor/service/engine/execute/SCM_REB$SYS_MasterData_DeleteDataService:
    params:
      request:
        id: 0
      modelKey: null
    serviceKey: SCM_REB$SYS_MasterData_DeleteDataService
  /api/trantor/service/engine/execute/SCM_REB$SYS_MasterData_UpdateDataService:
    params:
      request: {}
      modelKey: null
    serviceKey: SCM_REB$SYS_MasterData_UpdateDataService
  /api/trantor/service/engine/execute/SCM_REB$SYS_MasterData_SaveDataService:
    params:
      request: {}
      modelKey: null
    serviceKey: SCM_REB$SYS_MasterData_SaveDataService
  /api/trantor/service/engine/execute/SCM_REB$SYS_FindDataByIdsService:
    params:
      selectFields:
      - selectFields:
        - {}
        field: null
      request:
        ids:
        - 0
      modelKey: null
    serviceKey: SCM_REB$SYS_FindDataByIdsService
  /api/trantor/service/engine/execute/SCM_REB$SYS_SaveDataService:
    params:
      request: {}
      modelKey: null
    serviceKey: SCM_REB$SYS_SaveDataService
  /api/trantor/service/engine/execute/SCM_REB$SYS_BatchCreateDataService:
    params:
      request:
      - {}
      modelKey: null
    serviceKey: SCM_REB$SYS_BatchCreateDataService
  /api/trantor/service/engine/execute/SCM_REB$SYS_BatchDeleteDataService:
    params:
      request:
        ids:
        - 0
      modelKey: null
    serviceKey: SCM_REB$SYS_BatchDeleteDataService
  /api/trantor/service/engine/execute/SCM_REB$SYS_QueryStatisticsService:
    params:
      request:
        aggregateField: null
        conditionItems: null
        groupByFields:
        - null
        conditionGroup: null
        aggregateFunc: null
      modelKey: null
    serviceKey: SCM_REB$SYS_QueryStatisticsService
  /api/trantor/service/engine/execute/SCM_REB$SYS_CopyAndCreateDataByIdsService:
    params:
      request:
        ids:
        - 0
      modelKey: null
    serviceKey: SCM_REB$SYS_CopyAndCreateDataByIdsService
  /api/trantor/service/engine/execute/SCM_REB$SYS_PagingDataService:
    params:
      selectFields:
      - selectFields:
        - {}
        field: null
      request:
        sortOrders:
        - fieldAlias: null
          sortType: null
        pageable:
          conditionItems: null
          pageNo: 1
          conditionGroup: null
          pageSize: 20
      modelKey: null
    serviceKey: SCM_REB$SYS_PagingDataService
  /api/trantor/service/engine/execute/SCM_REB$SYS_BatchDeleteDataByIdsService:
    params:
      request:
        ids:
        - 0
      modelKey: null
    serviceKey: SCM_REB$SYS_BatchDeleteDataByIdsService
  /api/trantor/service/engine/execute/SCM_REB$SYS_MasterData_CreateDataService:
    params:
      request: {}
      modelKey: null
    serviceKey: SCM_REB$SYS_MasterData_CreateDataService
  /api/trantor/service/engine/execute/SCM_REB$SYS_CopyDataConverterService:
    params:
      request: {}
      modelKey: null
    serviceKey: SCM_REB$SYS_CopyDataConverterService
  /api/trantor/service/engine/execute/SCM_REB$SYS_CreateDataService:
    params:
      request: {}
      modelKey: null
    serviceKey: SCM_REB$SYS_CreateDataService
  /api/trantor/service/engine/execute/SCM_REB$SYS_BatchSaveDataService:
    params:
      request:
      - {}
      modelKey: null
    serviceKey: SCM_REB$SYS_BatchSaveDataService
  /api/trantor/service/engine/execute/SCM_REB$SYS_FindTreeDataService:
    params:
      request: {}
      modelKey: null
    serviceKey: SCM_REB$SYS_FindTreeDataService
  /api/trantor/service/engine/execute/SCM_REB$SYS_TreeSearchService:
    params:
      request:
        conditionItems: null
        conditionGroup: null
      modelKey: null
    serviceKey: SCM_REB$SYS_TreeSearchService
  /api/trantor/service/engine/execute/SCM_REB$SYS_COUNT_DATA_SERVICE:
    params:
      request:
      - null
      modelKey: null
    serviceKey: SCM_REB$SYS_COUNT_DATA_SERVICE
  /api/trantor/service/engine/execute/SCM_REB$REB_CB_HEAD_CANCEL_ACTION_SERVICE:
    params:
      request:
        id: {}
    serviceKey: SCM_REB$REB_CB_HEAD_CANCEL_ACTION_SERVICE
  /api/trantor/service/engine/execute/SCM_REB$REB_CB_HEAD_DETAIL_ACTION_SERVICE:
    params:
      request:
        id: null
    serviceKey: SCM_REB$REB_CB_HEAD_DETAIL_ACTION_SERVICE
  /api/trantor/service/engine/execute/SCM_REB$REB_POLICY_SUBMIT_APPROVAL_ACTION_SERVICE:
    params:
      request: {}
    serviceKey: SCM_REB$REB_POLICY_SUBMIT_APPROVAL_ACTION_SERVICE
  /api/trantor/service/engine/execute/SCM_REB$REB_POLICY_SAVE_ACTION_SERVICE:
    params:
      request: {}
    serviceKey: SCM_REB$REB_POLICY_SAVE_ACTION_SERVICE
  /api/trantor/service/engine/execute/SCM_REB$REB_POLICY_REJECT_ACTION_SERVICE:
    params:
      request: {}
    serviceKey: SCM_REB$REB_POLICY_REJECT_ACTION_SERVICE
  /api/trantor/service/engine/execute/SCM_REB$REB_CB_ITEM_UPDATE_AMOUNT_ACTION_SERVICE:
    params:
      request:
        periodId: {}
        updatedBy: {}
        originOrgId: 0
        cbItemCode: null
        slsAmt: 0
        cbHeadId: {}
        remark: null
        version: 0
        rebateAmt: 0
        createdAt: 0
        deleted: 0
        policyId: {}
        createdBy: {}
        requestId: null
        custId: {}
        slsQty: 0
        tenantId: 0
        periodKey: null
        id: 0
        rbRuleId: {}
        status: null
        updatedAt: 0
    serviceKey: SCM_REB$REB_CB_ITEM_UPDATE_AMOUNT_ACTION_SERVICE
  /api/trantor/service/engine/execute/SCM_REB$REB_CB_HEAD_APPROVE_ACTION_SERVICE:
    params:
      request: {}
    serviceKey: SCM_REB$REB_CB_HEAD_APPROVE_ACTION_SERVICE
  /api/trantor/service/engine/execute/SCM_REB$REB_CB_HEAD_REJECT_ACTION_SERVICE:
    params:
      request: {}
    serviceKey: SCM_REB$REB_CB_HEAD_REJECT_ACTION_SERVICE
  /api/trantor/service/engine/execute/SCM_REB$REB_CB_HEAD_SUBMIT_APPROVAL_ACTION_SERVICE:
    params:
      request:
        periodId: {}
        updatedBy: {}
        originOrgId: 0
        cbItemCode: null
        slsAmt: 0
        cbHeadId: {}
        remark: null
        version: 0
        rebateAmt: 0
        createdAt: 0
        deleted: 0
        policyId: {}
        createdBy: {}
        requestId: null
        custId: {}
        slsQty: 0
        tenantId: 0
        periodKey: null
        id: 0
        rbRuleId: {}
        status: null
        updatedAt: 0
    serviceKey: SCM_REB$REB_CB_HEAD_SUBMIT_APPROVAL_ACTION_SERVICE
  /api/trantor/service/engine/execute/SCM_REB$REB_CB_ITEM_BATCH_CANCEL_ACTION_SERVICE:
    params:
      request:
        ids:
        - null
    serviceKey: SCM_REB$REB_CB_ITEM_BATCH_CANCEL_ACTION_SERVICE
  /api/trantor/service/engine/execute/SCM_REB$REB_POLICY_APPROVE_ACTION_SERVICE:
    params:
      request: {}
    serviceKey: SCM_REB$REB_POLICY_APPROVE_ACTION_SERVICE
  /api/trantor/service/engine/execute/SCM_REB$REB_POLICY_PAGING_ACTION_SERVICE:
    params:
      request: {}
    serviceKey: SCM_REB$REB_POLICY_PAGING_ACTION_SERVICE
  /api/trantor/service/engine/execute/SCM_REB$REB_CB_HEAD_CONFIRM_DETAILS_ACTION_SERVICE:
    params:
      request:
        ids:
        - null
    serviceKey: SCM_REB$REB_CB_HEAD_CONFIRM_DETAILS_ACTION_SERVICE
  /api/trantor/service/engine/execute/SCM_REB$REB_POLICY_DISABLE_ACTION_SERVICE:
    params:
      request: {}
    serviceKey: SCM_REB$REB_POLICY_DISABLE_ACTION_SERVICE
  /api/trantor/service/engine/execute/SCM_REB$REB_CB_HEAD_PAGING_ACTION_SERVICE:
    params:
      request: {}
    serviceKey: SCM_REB$REB_CB_HEAD_PAGING_ACTION_SERVICE
  /api/trantor/service/engine/execute/SCM_REB$REB_CB_ITEM_CANCEL_ACTION_SERVICE:
    params:
      request: {}
    serviceKey: SCM_REB$REB_CB_ITEM_CANCEL_ACTION_SERVICE
  /api/trantor/service/engine/execute/SCM_REB$REB_POLICY_DELETE_ACTION_SERVICE:
    params:
      request: {}
    serviceKey: SCM_REB$REB_POLICY_DELETE_ACTION_SERVICE
  /api/trantor/service/engine/execute/SCM_REB$REB_POLICY_ENABLE_ACTION_SERVICE:
    params:
      request: {}
    serviceKey: SCM_REB$REB_POLICY_ENABLE_ACTION_SERVICE
  /api/trantor/service/engine/execute/SCM_REB$REB_POLICY_PERIOD_RECALC_ACTION_SERVICE:
    params:
      request:
        periodId: 0
    serviceKey: SCM_REB$REB_POLICY_PERIOD_RECALC_ACTION_SERVICE
  /api/trantor/service/engine/execute/SCM_REB$REB_POLICY_DETAIL_ACTION_SERVICE:
    params:
      request:
        policyCode: null
        soItemTypeIds:
        - {}
        createdAt: 0
        requestId: null
        rebDocType: null
        id: 0
        soTypeIds:
        - {}
        updatedAt: 0
        slsOrgIds:
        - {}
        dnItemTypeIds:
        - {}
        rebOrders:
        - {}
        updatedBy: {}
        originOrgId: 0
        policyName: null
        comOrgId: {}
        settAccTypeId: {}
        periodBeginAt: 0
        rebPeriods:
        - {}
        acquireType: null
        version: 0
        slsDcIds:
        - {}
        dnTypeIds:
        - {}
        invOrgIds:
        - {}
        periodType: null
        deleted: 0
        createdBy: {}
        rebRules:
        - {}
        tenantId: 0
        periodEndAt: 0
        status: null
    serviceKey: SCM_REB$REB_POLICY_DETAIL_ACTION_SERVICE
