# SCM配置数据查询定义
base_info:
  # 基础配置数据
  # 币种信息
  currency_info:
    sql: |
      SELECT id as 'curr_id', curr_code, curr_name 
      FROM gen_curr_type_cf 
      WHERE curr_name='人民币' AND deleted=0 LIMIT 1
    description: "查询人民币的基础信息"
    insert_sql: |
      INSERT INTO `gen_curr_type_cf` (`curr_code`, `curr_name`, `curr_iso_name`, `decimal_place`, `symbol`, `remark`, `created_by`, `updated_by`, `created_at`, `updated_at`, `version`, `deleted`, `request_id`, `origin_org_id`, `tenant_id`) VALUES
      ('CNY', '人民币', NULL, NULL, NULL, NULL, 1, 1, NOW(), NOW(), 0, 0, NULL, 0, 0);
    validation:
      min_records: 1
      required_fields: ["curr_id", "curr_code", "curr_name"]

  # 国家信息
  country_info:
    sql: |
      SELECT id as 'coun_id', coun_code, coun_name 
      FROM gen_coun_type_cf 
      WHERE coun_code='CHINA' AND deleted=0 LIMIT 1
    description: "查询中国的基础信息"
    insert_sql: |
      INSERT INTO `gen_coun_type_cf` (`coun_code`, `coun_name`, `default_relv`, `language_id`, `curr_id`, `timezone_id`, `created_by`, `updated_by`, `created_at`, `updated_at`, `version`, `deleted`, `request_id`, `origin_org_id`, `tenant_id`) VALUES
      ('CHINA', '中国', (select id from gen_language_type_cf where language_code='zh-CN'), (select id from gen_curr_type_cf where curr_code='CNY'), NULL, 1, 1,now(),now(), 0, 0, NULL, 0, 0);
    validation:
      min_records: 1
      required_fields: ["coun_id", "coun_code", "coun_name"]

  # 时区信息
  timezone_info:
    sql: |
     select id, timezone_code, timezone_format from gen_timezone_type_cf where `status`='ENABLED' and deleted=0 limit 1
    description: "查询时区信息"
    insert_sql: |
      INSERT INTO `gen_timezone_type_cf`(`created_by`,`updated_by`,`created_at`,`updated_at`,`version`,`deleted`,`timezone_code`,`timezone_format`,`is_summer_time`,`summer_time_start`,`summer_time_end`,`status`,`origin_org_id`,`request_id`,`timezone_desc`,`coun_id`,`timezone_district`)
      VALUES (1,1,NOW(),NOW(),1,0,'Asia/Shanghai','UTC+8',0,NULL,NULL,'ENABLED',0,NULL,'东八区',(SELECT id FROM `gen_coun_type_cf` WHERE coun_code='CHINA' AND deleted=0 LIMIT 1),NULL);
    validation:
      min_records: 1
      required_fields: ["id", "timezone_code", "timezone_format"]

  # 工作日日历
  gen_wc_head_info:
    sql: |
      SELECT id as 'gen_wc_head_id', wc_head_code, wc_head_name 
      FROM gen_wc_head_cf 
      WHERE deleted=0 LIMIT 1
    description: "查询工作日日历信息"

  # 期间类型  
  calender_info:
    sql: |
     SELECT id ,calendar_code,calendar_name,`status`
      FROM fin_common_calendar_head_cf  
      WHERE deleted=0 and `status`= 'ENABLED' LIMIT 1
    description: "查询期间类型信息"


  # 地址信息，四级地址ID
  addr_info:
    sql: |
      SELECT id FROM gen_addr_type_cf  WHERE  deleted=0  and  is_leaf=1 and level=4 limit 1
    description: "查询地址信息"
  
  # 汇率类型
  exchange_rate_type_info:
    sql: |
      SELECT id as 'exchange_rate_type_id', 
             type_code as 'exchange_rate_type_code', 
             type_name as 'exchange_rate_type_name' 
      FROM gen_curr_exchange_rate_type_cf 
      WHERE type_code='HR' AND deleted=0 LIMIT 1
    description: "查询汇率类型信息"
    insert_sql: |
      INSERT INTO `gen_curr_exchange_rate_type_cf` (`type_code`, `type_name`, `created_by`, `updated_by`, `created_at`, `updated_at`, `version`, `deleted`, `request_id`, `origin_org_id`, `tenant_id`) VALUES
      ('HR', '固定汇率', 1, 1, NOW(), NOW(), 0, 0, NULL, 0, 0);
    validation:
      min_records: 1
      required_fields: ["exchange_rate_type_id", "exchange_rate_type_code", "exchange_rate_type_name"]

  # 计量单位信息
  uom_info:
    qty_uom_info:
      sql: |
        SELECT id as 'uom_id', uom_code, uom_type, uom_desc 
        FROM gen_uom_type_cf 
        WHERE deleted=0 and uom_type='QTY' and uom_code='QTY' limit 1;
      description: "查询数量计量单位信息"
    mass_uom_info:
      sql: |
        SELECT id as 'uom_id', uom_code, uom_type, uom_desc 
        FROM gen_uom_type_cf 
        WHERE deleted=0 and uom_type='MASS'and uom_code='KG' limit 1;
      description: "查询质量计量单位信息"
    len_uom_info:
      sql: |
        SELECT id as 'uom_id', uom_code, uom_type, uom_desc 
        FROM gen_uom_type_cf 
        WHERE deleted=0 and uom_type='L' limit 1;
      description: "查询长度计量单位信息"
    volume_uom_info:
      sql: |
        SELECT id as 'uom_id', uom_code, uom_type, uom_desc 
        FROM gen_uom_type_cf 
        WHERE deleted=0 and uom_type='VOL' limit 1;
      description: "查询体积计量单位信息"

  # # 银行信息
  # bank_info:
  #   sql: |
  #    SELECT  a.id AS 'bank_id',a.bank_code AS 'bank_code',a.bank_name AS 'bank_name',b.id AS 'sub_bank_id',b.sub_bank_code AS 'sub_bank_code',b.sub_bank_name AS 'sub_bank_name' FROM gen_bank_cf a INNER JOIN  gen_sub_bank_cf b ON a.id = b.gen_bank_cf_id LIMIT 1
  #   description: "查询银行信息"

  # 税码信息
  tax_info:
    sql: |
      select id, tax_code,taxcate,tax  
      from gen_tax_type_cf 
      where deleted=0
    description: "查询税码信息"
    validation:
      min_records: 1
      required_fields: ["id", "tax_code", "taxcate", "tax"]

    # associated_tax_code