# SCM配置数据查询定义
base_info:
  # 基础配置数据
  # 币种信息
  currency_info:
    sql: |
      SELECT id as 'curr_id', curr_code, curr_name 
      FROM gen_curr_type_cf 
      WHERE curr_code='CNY' AND deleted=0 LIMIT 1
    description: "查询人民币的基础信息"
    insert_sql: |
      INSERT INTO `gen_curr_type_cf` (`curr_code`, `curr_name`, `curr_iso_name`, `decimal_place`, `symbol`, `remark`, `created_by`, `updated_by`, `created_at`, `updated_at`, `version`, `deleted`, `request_id`, `origin_org_id`, `tenant_id`) VALUES
      ('CNY', '人民币', NULL, NULL, NULL, NULL, 1, 1, NOW(), NOW(), 0, 0, NULL, 0, 0);
    validation:
      min_records: 1
      required_fields: ["curr_id", "curr_code", "curr_name"]


  # 语言信息
  language_info:
      sql: |
        SELECT id as 'language_id', language_code, language_name 
        FROM gen_language_type_cf 
        WHERE language_code='CHINESE' AND deleted=0 LIMIT 1
      description: "查询中文的基础信息"
      insert_sql: |
        INSERT INTO `gen_language_type_cf` (`created_by`, `updated_by`, `created_at`, `updated_at`, `version`, `deleted`, `language_code`, `language_name`, `origin_org_id`, `request_id`) VALUES
        ( 1, 1, NOW(), NOW(), 0, 0, 'zh-CN', "简体中文", 0, NULL);
      validation:
        min_records: 1
        required_fields: ["language_id", "language_code", "language_name"]

  # 国家信息
  country_info:
    sql: |
      SELECT id as 'coun_id', coun_code, coun_name 
      FROM gen_coun_type_cf 
      WHERE coun_code='CHINA' AND deleted=0 LIMIT 1
    description: "查询中国的基础信息"
    insert_sql: |
      INSERT INTO `gen_coun_type_cf` (`coun_code`, `coun_name`, `default_relv`, `language_id`, `curr_id`, `timezone_id`, `created_by`, `updated_by`, `created_at`, `updated_at`, `version`, `deleted`, `request_id`, `origin_org_id`, `tenant_id`) VALUES
      ('CHINA', '中国', (select id from gen_language_type_cf where language_code='zh-CN'), (select id from gen_curr_type_cf where curr_code='CNY'), NULL, 1, 1,now(),now(), 0, 0, NULL, 0, 0);
    validation:
      min_records: 1
      required_fields: ["coun_id", "coun_code", "coun_name"]

  # 时区信息
  timezone_info:
    sql: |
     select id, timezone_code, timezone_format from gen_timezone_type_cf where `status`='ENABLED' and deleted=0 limit 1
    description: "查询时区信息"
    insert_sql: |
      INSERT INTO `gen_timezone_type_cf`(`created_by`,`updated_by`,`created_at`,`updated_at`,`version`,`deleted`,`timezone_code`,`timezone_format`,`is_summer_time`,`summer_time_start`,`summer_time_end`,`status`,`origin_org_id`,`request_id`,`timezone_desc`,`coun_id`,`timezone_district`)
      VALUES (1,1,NOW(),NOW(),1,0,'Asia/Shanghai','UTC+8',0,NULL,NULL,'ENABLED',0,NULL,'东八区',(SELECT id FROM `gen_coun_type_cf` WHERE coun_code='CHINA' AND deleted=0 LIMIT 1),NULL);
    validation:
      min_records: 1
      required_fields: ["id", "timezone_code", "timezone_format"]

  # 工作日日历
  gen_wc_head_info:
    sql: |
      SELECT id as 'gen_wc_head_id', wc_head_code, wc_head_name 
      FROM gen_wc_head_cf 
      WHERE deleted=0 LIMIT 1
    description: "查询工作日日历信息"

  # 期间类型  
  calender_info:
    sql: |
     SELECT id ,calendar_code,calendar_name,`status`
      FROM fin_common_calendar_head_cf  
      WHERE deleted=0 and `status`= 'ENABLED' LIMIT 1
    description: "查询期间类型信息"
  
  # 汇率类型
  exchange_rate_type_info:
    sql: |
      SELECT id as 'exchange_rate_type_id', 
             type_code as 'exchange_rate_type_code', 
             type_name as 'exchange_rate_type_name' 
      FROM gen_curr_exchange_rate_type_cf 
      WHERE type_code='HR' AND deleted=0 LIMIT 1
    description: "查询汇率类型信息"
    insert_sql: |
      INSERT INTO `gen_curr_exchange_rate_type_cf` (`type_code`, `type_name`, `created_by`, `updated_by`, `created_at`, `updated_at`, `version`, `deleted`, `request_id`, `origin_org_id`, `tenant_id`) VALUES
      ('HR', '固定汇率', 1, 1, NOW(), NOW(), 0, 0, NULL, 0, 0);
    validation:
      min_records: 1
      required_fields: ["exchange_rate_type_id", "exchange_rate_type_code", "exchange_rate_type_name"]

  # 客户税信息
  cust_tax_type_info:
    sql: |
      SELECT id as 'cust_tax_type_id', tax_class_code, tax_class_desc 
      FROM gen_cust_tax_type_cf 
      WHERE deleted=0
    description: "查询客户税信息"
    validation:
      min_records: 0
      required_fields: ["cust_tax_type_id", "tax_class_code", "tax_class_desc"]
  # 计量单位信息
  uom_info:
    sql: |
      SELECT id as 'uom_id', uom_code, uom_type, uom_desc 
      FROM gen_uom_type_cf 
      WHERE deleted=0
    description: "查询计量单位信息"
    validation:
      min_records: 0
      required_fields: ["uom_id", "uom_code", "uom_type", "uom_desc"]

  # 银行信息
  bank_info:
    sql: |
      SELECT id as 'bank_id', bank_code, bank_name, bank_mne_code 
      FROM gen_bank_cf 
      WHERE deleted=0 LIMIT 1
    description: "查询银行信息"
    validation:
      min_records: 1
      required_fields: ["bank_id", "bank_code", "bank_name", "bank_mne_code"]

  # 组织信息
  # 公司组织
  com_org_info:
    sql: |
      SELECT id, org_code, org_name, org_status, org_dimension_code, org_business_type_code
      FROM org_struct_md
      WHERE org_status="ENABLED" AND org_dimension_code="SCM_ORG_GRP" AND org_code="AUTOTEST_COM_ORG" AND org_business_type_codes= '[\"COM_ORG\"]' LIMIT 1
    description: "查询公司组织信息"
    validation:
      min_records: 1
      required_fields: ["id", "org_code", "org_name", "org_status", "org_dimension_code", "org_business_type_code"]

  # 采购组织
  pur_org_info:
    sql: |
      SELECT id, org_code, org_name, org_status, org_dimension_code, org_business_type_code
      FROM org_struct_md
      WHERE org_status='ENABLED' AND org_dimension_code='SCM_ORG_GRP' AND org_code LIKE 'AUTOTEST%' AND org_business_type_codes = '[\"PUR_ORG\"]' LIMIT 1
    description: "查询采购组织信息"
    validation:
      min_records: 1
      required_fields: ["id", "org_code", "org_name", "org_status", "org_dimension_code", "org_business_type_code"]

  # 库存组织
  inv_org_info:
    sql: |
      SELECT id, org_code, org_name, org_status, org_dimension_code, org_business_type_code
      FROM org_struct_md
      WHERE org_status='ENABLED' AND org_dimension_code='SCM_ORG_GRP' AND org_code LIKE 'AUTOTEST%' AND org_business_type_codes = '[\"INV_ORG\"]' LIMIT 1
    description: "查询库存组织信息"
    validation:
      min_records: 1
      required_fields: ["id", "org_code", "org_name", "org_status", "org_dimension_code", "org_business_type_code"]

  # 销售组织
  sls_org_info:
    sql: |
      SELECT id, org_code, org_name, org_status, org_dimension_code, org_business_type_code
      FROM org_struct_md
      WHERE org_status='ENABLED' AND org_dimension_code='SCM_ORG_GRP' AND org_code LIKE 'AUTOTEST%' AND org_business_type_codes = '[\"SLS_ORG\"]' LIMIT 1
    description: "查询销售组织信息"
    validation:
      min_records: 1
      required_fields: ["id", "org_code", "org_name", "org_status", "org_dimension_code", "org_business_type_code"]

  # 计划组织
  pln_org_info:
    sql: |
      SELECT id, org_code, org_name, org_status, org_dimension_code, org_business_type_code
      FROM org_struct_md
      WHERE org_status='ENABLED' AND org_dimension_code='SCM_ORG_GRP' AND org_code LIKE 'AUTOTEST%' AND org_business_type_codes = '[\"PLN_ORG\"]' LIMIT 1
    description: "查询计划组织信息"
    validation:
      min_records: 1
      required_fields: ["id"]

  # 默认员工
  employee_info:
    sql: |
      SELECT id, name
      FROM org_employee_md
      WHERE name='admin' LIMIT 1
    description: "查询默认员工信息"
    validation:
      min_records: 1
      required_fields: ["id", "name"]

  # 销售渠道
  org_sls_dc_info:
    sql: |
      SELECT id, `code`, `name`
      FROM org_sls_dc_cf
      WHERE `code` like 'AUTOTEST_SLS_DC%' AND deleted=0 LIMIT 1
    description: "查询销售渠道信息"
    validation:
      min_records: 1
      required_fields: ["id", "code", "name"]


  # 库存地点
  inv_loc_info:
    sql: |
      SELECT id, org_code, org_name, org_status, org_dimension_code, org_business_type_code
      FROM org_struct_md
      WHERE org_status='ENABLED' AND org_dimension_code='SCM_ORG_GRP' AND org_code LIKE 'AUTOTEST%' AND org_business_type_codes = '[\"INV_LOC\"]' LIMIT 1
    description: "查询库存地点信息"
    validation:
      min_records: 1
      required_fields: ["id", "org_code", "org_name", "org_status", "org_dimension_code", "org_business_type_code"]

  # 合作伙伴
  # 供应商
  vend_info:
    sql: |
      SELECT id, `code`, `name`, `status`
      FROM gen_business_partner_md
      WHERE `status` = 'ENABLED' AND JSON_CONTAINS(partner_identity, '"SUPPLIER"') AND `code`='AUTOTEST_VEND' LIMIT 1
    description: "查询供应商信息"
    validation:
      min_records: 1
      required_fields: ["id", "code", "name", "status"]

  # 客户
  cust_info:
    sql: |
      SELECT id, `code`, `name`, `status`
      FROM gen_business_partner_md
      WHERE `status` = 'ENABLED' AND JSON_CONTAINS(partner_identity, '"CUSTOMER"') AND `code`='AUTOTEST_CUST' LIMIT 1
    description: "查询客户信息"
    validation:
      min_records: 1
      required_fields: ["id", "code", "name", "status"]

  # 税码信息
  tax_info:
    sql: |
      select id, tax_code,taxcate,tax  
      from gen_tax_type_cf 
      where deleted=0
    description: "查询税码信息"
    validation:
      min_records: 1
      required_fields: ["id", "tax_code", "taxcate", "tax"]

    # associated_tax_code