# 期间类型 
calender_info:
  calender_head_info:
    sql: |
     select  id,calendar_code,calendar_name,`status` from fin_common_calendar_head_cf where calendar_code = 'AUTOTEST_CALEDAR' and status='ENABLED' and  deleted=0 limit 1; 
    description: "查询期间类型信息"

  calender_item_info:
    sql: |
     select  id,period_code,period_name,`status`,period_type from fin_common_calendar_item_cf where deleted=0 and gen_calendar_head_cf_id = (select  id from fin_common_calendar_head_cf where calendar_code = 'AUTOTEST_CALEDAR' and status='ENABLED' and  deleted=0 limit 1);
    description: "查询期间行信息"