# 期间类型 
calender_info:
  calender_head_info:
    sql: |
     select  id,calendar_code,calendar_name,`status` from fin_common_calendar_head_cf where calendar_code = 'AUTOTEST_CALEDAR' and status='ENABLED' and  deleted=0 limit 1; 
    description: "查询期间类型信息"

  calender_item_info:
    sql: |
     select  id,period_code,period_name,`status`,period_type from fin_common_calendar_item_cf where deleted=0 and gen_calendar_head_cf_id = (select  id from fin_common_calendar_head_cf where calendar_code = 'AUTOTEST_CALEDAR' and status='ENABLED' and  deleted=0 limit 1);
    description: "查询期间行信息"

# 结算单配置
sett_doc_info:
  sett_doc_type_info:
    sql: |
     select id ,sett_doc_type_code,sett_doc_type_name from fin_sett_doc_type_cf where deleted=0 and sett_doc_type_code='E_SLS' limit 1;
    description: "查询外部-销售（标准）结算单类型信息"

# 结算项配置
sett_item_info:
  sett_item_type_info:
    sql: |
<<<<<<< HEAD
     select id,bt_class,sett_item_type_code,sett_item_type_name,sett_doc_type_code,is_acq_cost,is_count_qty  from fin_sett_item_type_cf where deleted=0;
    description: "查询结算项类型信息"
=======
     select id,sett_item_type_code,sett_item_type_name  from fin_sett_item_type_cf where deleted=0  and sett_item_type_code='E_SLS_GOODS' limit 1;
    description: "查询外部-销售（标准）结算项类型信息"
>>>>>>> 881d58d822d2eec18d284fbe88ccf33afe8f6209
#销售发票类型配置
sb_type_info:
  sb_type_info:
    sql: |
     select id,name,push_aes,auto_push_aes from fin_tm_sb_type_md where deleted=0 and sb_type_code='STND';
    description: "查询标准销售发票类型信息"