user_id: ["user_info", "user_info", "id"]
cust_id: ["partner_info", "cust_info", "id"]
so_type_id: ["base_info", "so_type_info", "id"]
sls_org_id: ["org_info", "sls_org_info", "id"]
pur_org_id: ["org_info", "pur_org_info", "id"]
inv_org_id: ["org_info", "inv_org_info", "id"]
com_org_id: ["org_info", "com_org_info", "id"]
pln_org_id: ["org_info", "pln_org_info", "id"]
employee_id: ["base_info", "employee_info", "id"]
sls_dc_id: ["base_info", "sales_channel_info", "id"]
inv_loc_id: ["material_info", "inv_loc_info", "id"]
exchange_rate_type_id: ["base_info", "exchange_rate_type_info", "exchange_rate_type_id"]
base_curr_id: ["base_info", "currency_info", "curr_id"]
sls_curr_id: ["base_info", "currency_info", "curr_id"]
currency_id: ["base_info", "currency_info", "curr_id"]
language_id: ["base_info", "language_info", "language_id"]
country_id: ["base_info", "country_info", "coun_id"]
timezone_id: ["base_info", "timezone_info", "timezone_id"]
cust_tax_type_id: ["base_info", "cust_tax_type_info", "cust_tax_type_id"]
uom_id: ["base_info", "uom_info", "uom_id"]
bank_id: ["base_info", "bank_info", "bank_id"]
vend_id: ["partner_info", "vend_info", "id"]
atp_group_id: ["material_info", "atp_group_info", "id"]
inv_type_id: ["material_info", "inv_type_info", "id"]
tax_id: ["base_info", "tax_info", "id"]