# MD配置数据查询定义
org_info:
  # 币种信息
  org_biz_type_cf:
    sql: |
     select id,`code`,`name` from org_business_type_cf where deleted=0
    description: "查询组织类型信息"

  # 组织属性
  org_attr_cf:  
    sql: |
      select id,attr_field, attr_code,attr_name from  gen_attr_cf where attr_class_code='ORG' and `status` = 'ENABLED' and deleted=0;
    description: "查询组织属性信息"

  # 组织身份
  org_identity_cf:
    sql: |
     select id,`code`,`name`  from org_identity_cf where `code`= "AUTOTEST_ORG_IDENTITY"  and  `status`="ENABLED" and deleted=0
    description: "查询组织身份信息"

  # 组织维度
  org_dimension_cf:
    sql: |
      select id,org_dimension_code,org_dimension_name from org_dimension_cf  where `org_dimension_code`= "SCM_ORG_GRP" and deleted =0  and `status`="ENABLED" limit 2
    description: "查询组织维度信息"

  # 组织单位
  # 集团公司
   # 公司组织
  gr_come_org_info:
    sql: |
      SELECT id, org_code, org_name, org_status, org_dimension_code, org_business_type_code
      FROM org_struct_md
      WHERE org_status="ENABLED" AND org_dimension_code="SCM_ORG_GRP" AND org_code="AUTOTEST_GR_ORG" and  deleted=0  LIMIT 1
    description: "查询集团公司组织信息"

  # 公司组织
  com_org_info:
    sql: |
      SELECT id, org_code, org_name, org_status, org_dimension_code, org_business_type_code
      FROM org_struct_md
      WHERE org_status="ENABLED" AND org_dimension_code="SCM_ORG_GRP" AND org_code="AUTOTEST_COM_ORG" AND org_business_type_codes= '[\"COM_ORG\"]' LIMIT 1
    description: "查询公司组织信息"

  # 采购组织
  pur_org_info:
    sql: |
      SELECT id, org_code, org_name, org_status, org_dimension_code, org_business_type_code
      FROM org_struct_md
      WHERE org_status='ENABLED' AND org_dimension_code='SCM_ORG_GRP' AND org_code LIKE 'AUTOTEST%' AND org_business_type_codes = '[\"PUR_ORG\"]' LIMIT 1
    description: "查询采购组织信息"
    validation:
      min_records: 1
      required_fields: ["id", "org_code", "org_name", "org_status", "org_dimension_code", "org_business_type_code"]

  # 库存组织
  inv_org_info:
    sql: |
      SELECT id, org_code, org_name, org_status, org_dimension_code, org_business_type_code
      FROM org_struct_md
      WHERE org_status='ENABLED' AND org_dimension_code='SCM_ORG_GRP' AND org_code LIKE 'AUTOTEST%' AND org_business_type_codes = '[\"INV_ORG\"]' LIMIT 1
    description: "查询库存组织信息"
    validation:
      min_records: 1
      required_fields: ["id", "org_code", "org_name", "org_status", "org_dimension_code", "org_business_type_code"]

  # 库存地点
  inv_loc_info:
    sql: |
      SELECT id, org_code, org_name, org_status, org_dimension_code, org_business_type_code
      FROM org_struct_md
      WHERE org_status='ENABLED' AND org_dimension_code='SCM_ORG_GRP' AND org_code LIKE 'AUTOTEST%' AND org_business_type_codes = '[\"INV_LOC\"]' LIMIT 1
    description: "查询库存地点信息"
    validation:
      min_records: 1
      required_fields: ["id", "org_code", "org_name", "org_status", "org_dimension_code", "org_business_type_code"]


  # 销售组织
  sls_org_info:
    sql: |
      SELECT id, org_code, org_name, org_status, org_dimension_code, org_business_type_code
      FROM org_struct_md
      WHERE org_status='ENABLED' AND org_dimension_code='SCM_ORG_GRP' AND org_code LIKE 'AUTOTEST%' AND org_business_type_codes = '[\"SLS_ORG\"]' LIMIT 1
    description: "查询销售组织信息"
    validation:
      min_records: 1
      required_fields: ["id", "org_code", "org_name", "org_status", "org_dimension_code", "org_business_type_code"]

  # 计划组织
  pln_org_info:
    sql: |
      SELECT id, org_code, org_name, org_status, org_dimension_code, org_business_type_code
      FROM org_struct_md
      WHERE org_status='ENABLED' AND org_dimension_code='SCM_ORG_GRP' AND org_code LIKE 'AUTOTEST%' AND org_business_type_codes = '[\"PLN_ORG\"]' LIMIT 1
    description: "查询计划组织信息"
    validation:
      min_records: 1
      required_fields: ["id"]

  # 销售渠道
  sls_dc_md:
    sql: |
      select id,`code`,`name`,is_online,`status`  from sls_dc_md where `code` like 'AUTOTEST_%' and deleted=0 and `status`	='ENABLED'; 
    description: "查询销售渠道信息"

  # 仓库信息
  inv_wh_md:
    sql: |
      select id,`code`,`name` from inv_wh_md where deleted=0 and `status`="ENABLED" limit 1
    description: "查询仓库信息"

  # 仓位信息
  inv_bin_rec_md:
    sql: |
      select inv_wh_id, inv_area_id, id,`code`,`name` from inv_bin_md where code = 'AUTOTEST_REC_BIN' limit 1
    description: "查询绑定的仓库id、收货仓储区id、收货仓位id"

  inv_bin_send_md:
    sql: |
      select inv_wh_id, inv_area_id, id,`code`,`name` from inv_bin_md where code = 'AUTOTEST_SEND_BIN' limit 1
    description: "查询绑定的仓库id、发货仓储区id、发货仓位id"

  # 采购移动类型信息
  inv_mvm_type_cf_pur:
    sql: |
      select id,`code`,`name` from inv_mvm_type_cf where code='00301100' limit 1
    description: "查询采购移动类型信息"

  # 销售移动类型信息
  inv_mvm_type_cf_sls:
    sql: |
      select id,`code`,`name` from inv_mvm_type_cf where code='20401100' limit 1
    description: "查询销售移动类型信息"

  # 默认员工
  employee_info:
    sql: |
      SELECT id, name
      FROM org_employee_md
      WHERE name='admin' LIMIT 1
    description: "查询默认员工信息"

mat_info:
  
  # 物料类目
  mat_cate_md:
    sql: |
      select id,`mat_cate_code`,`mat_cate_name` from gen_mat_cate_md where deleted=0 and `status`="ENABLED" and mat_cate_code like 'AUTOTEST_%'  limit 1
    description: "查询物料类目信息"
  # 物料品牌
  mat_brand_md:
    sql: |
      select id,`brand_code`,	`brand_name` from gen_brand_md where deleted=0 and brand_code like 'AUTOTEST_%'  limit 1
    description: "查询物料品牌信息"

  # 物料类型
  mat_type_cf:
    FINP:
      sql: |
        select id,	`mat_type_code`,`mat_type_name` from gen_mat_type_cf where deleted=0 and `mat_type_code`='FINP' limit 1;
      description: "查询成品物料类型信息"
    SERV:
      sql: |
        select id,	`mat_type_code`,`mat_type_name` from gen_mat_type_cf where deleted=0 and `mat_type_code`='SERV' limit 1;
      description: "查询服务物料类型信息"
    RAW:
      sql: |
        select id,	`mat_type_code`,`mat_type_name` from gen_mat_type_cf where deleted=0 and `mat_type_code`='RAW' limit 1;
      description: "查询原材料物料类型信息"

  # ATP检查组
  inv_atp_group_md:
    sql: |
      select id,`code`,`name` from inv_atp_group_md where deleted=0 limit 1
    description: "查询ATP检查组信息"

  # 物料标签
  gen_label_md:
    sql: |
      select id,`name`,usage_type from gen_label_md where usage_type='MAT'  and `name`='自动化' and `status`="ENABLED" limit 1
    description: "查询标签信息"
  # 物料主数据
  mat_md:
    FINP:
      sql: |
        select id,mat_code,mat_name from gen_mat_md where deleted=0 and mat_code like "AUTOTEST_MAT_FINP" and `status`="ENABLED"
      description: "查询成品物料主数据信息"
    SERV:
      sql: |
        select id,mat_code,mat_name from gen_mat_md where deleted=0 and mat_code like "AUTOTEST_MAT_SERV" and `status`="ENABLED"
      description: "查询服务物料主数据信息"
partner_info:
  # 合作伙伴类型
  business_partner_type_cf:
    out_cust:
      sql: |
        select id,`code`,`name`,`status` from gen_business_partner_type_cf where `code` like 'AUTOTEST_OUT_CUST' and deleted=0 limit 1;
      description: "查询客户类型信息"
    inter_cust:
      sql: |
        select id,`code`,`name`,`status` from gen_business_partner_type_cf where `code` like 'AUTOTEST_INTER_CUST' and deleted=0 limit 1;
      description: "查询内部客户类型信息"
    person_cust:  
      sql: |
        select id,`code`,`name`,`status` from gen_business_partner_type_cf where `code` like 'AUTOTEST_PERSON_CUST' and deleted=0 limit 1;
      description: "查询个人客户类型信息"
    out_supplier:
      sql: |
        select id,`code`,`name`,`status` from gen_business_partner_type_cf where `code` like 'AUTOTEST_OUT_SUPPLIER' and deleted=0 limit 1;
      description: "查询供应商类型信息"
    outsea_supplier:
      sql: |
        select id,`code`,`name`,`status` from gen_business_partner_type_cf where `code` like 'AUTOTEST_OUTSEA_SUPPLIER' and deleted=0 limit 1;
      description: "查询海外供应商类型信息"
    inter_supplier:
      sql: |
        select id,`code`,`name`,`status` from gen_business_partner_type_cf where `code` like 'AUTOTEST_INTER_SUPPLIER' and deleted=0 limit 1; 
      description: "查询内部供应商类型信息"
    serv_supplier:
      sql: |
        select id,`code`,`name`,`status` from gen_business_partner_type_cf where `code` like 'AUTOTEST_SERV_SUPPLIER' and deleted=0 limit 1;
      description: "查询服务供应商类型信息"

  # 相关方类型
  partner_type_cf:
    sls_partner_type:
      sql: |
        select id,partner_code,partner_name from gen_partner_type_cf where partner_code='AUTOTEST_SLS_PTN_TYPE' and deleted=0 limit 1;
      description: "查询销售相关方类型信息"
    pur_partner_type:
      sql: |
        select id,partner_code,partner_name from gen_partner_type_cf where partner_code='AUTOTEST_PUR_PTN_TYPE' and deleted=0 limit 1;
      description: "查询采购相关方类型信息"

  # 文本类型
  text_type_cf:
    sls_text_type:
      sql: |
        select id,text_code ,text_name from  gen_text_type_cf where  text_code = 'AUTOTEST_SLS_TEXT_TYPE'  and deleted=0 limit 1;
      description: "查询销售文本类型信息"
    pur_text_type:
      sql: |
        select id,text_code ,text_name from  gen_text_type_cf where  text_code = 'AUTOTEST_PUR_TEXT_TYPE'  and deleted=0 limit 1;
      description: "查询采购文本类型信息"
  # 供应商
  vend_info:
    sql: |
      SELECT id, `code`, `name`, `status`
      FROM gen_business_partner_md
      WHERE `status` = 'ENABLED' AND JSON_CONTAINS(partner_identity, '"SUPPLIER"') AND `code`='AUTOTEST_VEND' LIMIT 1
    description: "查询供应商信息"
    validation:
      min_records: 1
      required_fields: ["id", "code", "name", "status"]

  # 客户
  cust_info:
    sql: |
      SELECT id, `code`, `name`, `status`
      FROM gen_business_partner_md
      WHERE `status` = 'ENABLED' AND JSON_CONTAINS(partner_identity, '"CUSTOMER"') AND `code`='AUTOTEST_CUST' LIMIT 1
    description: "查询客户信息"
    validation:
      min_records: 1
      required_fields: ["id", "code", "name", "status"]


index_info:
  # 指标信息
  index_md:
    sql: |
      select id,gen_index_code,gen_index_name from gen_index_md where gen_index_code='AUTOTEST_INDEX_CODE' and deleted=0 limit 1;
    description: "查询指标信息"

dynamic_form_info:
  dynamic_form_template_md:
    cust_template:
      sql: |
        select id ,`name`,`desc` from gen_dynamic_form_template_md where name like '%(自动化)' and state='ENABLED' and template_type="gen_cust_dynamic_form_record_md" limit 1
      description: "查询客户动态表单模板信息"
    vend_template:
      sql: |
        select id ,`name`,`desc` from gen_dynamic_form_template_md where name like '%(自动化)' and state='ENABLED' and template_type="gen_vend_dynamic_form_record_md" limit 1
      description: "查询供应商动态表单模板信息"