# SLS配置数据查询定义
sls_config:
  # 订单类型信息
  so_type_info:
    sql: |
      SELECT id ,so_type_code,so_type_name,`status` FROM sls_so_type_cf WHERE deleted = 0 and status='ENABLED'
    description: "查询订单类型"

  # 订单行类型信息
  so_item_type_info:
    sql: |
      SELECT id, so_item_type_code, so_item_type_name,`status`  FROM sls_so_item_type_cf WHERE deleted = 0 and status='ENABLED'
    description: "查询订单行类型"

  # 订单类型和订单行类型分配    
  so_item_detm_info:
    sql: |
      SELECT so_item_type_id, so_type_id,mat_type_id, usage_type,parent_so_item_type_id,so_item_type_group_id FROM sls_so_item_detm_cf  WHERE deleted = 0
    description: "查询订单类型和订单行类型的分配" 


  # 订单行类型组信息
  so_item_type_group_info:
    sql: |
      select id,`code`,`name` from sls_so_item_type_group_cf where deleted=0
    description: "查询订单行项目类型组"
