version: "1.1"
name: "CI Pipeline"
stages:
  - stage:
      - git-checkout:
          alias: git-checkout
          description: 代码仓库克隆
          params:
            depth: 1

  - stage:
      - dockerfile:
          alias: pack-testapi
          description: 针对自定义 dockerfile 打包，产出可运行镜像
          params:
            path: Dockerfile
            workdir: ${git-checkout}

  - stage:
      - release:
          alias: release
          description: 用于打包完成时，向dicehub 提交完整可部署的dice.yml
          params:
            dice_yml: ${git-checkout}/dice.yml
            image:
              test-api: ${pack-testapi:OUTPUT:image}

  - stage:
      - dice:
          alias: dice
          description: 用于 Erda 平台部署应用服务
          params:
            release_id_path: ${release}