[pytest]
addopts = -v
markers =
    order: mark test execution order
    depends: mark test dependencies 
    smoke: 冒烟测试
    regression: 回归测试
    api: API测试
    database: 数据库测试

filterwarnings =
    ignore::pytest.PytestAssertRewriteWarning
