[pytest]
pythonpath = .
log_cli = true
log_cli_level = DEBUG
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
addopts = -v --alluredir=./reports/allure-results
markers =
    order: mark test execution order
    depends: mark test dependencies 

filterwarnings =
    ignore::pytest.PytestAssertRewriteWarning

# Allure configurations
allure_report_dir = ./reports/allure-results
allure_link_pattern = {}
allure_clear_old_results = True