[pytest]
addopts = 
    -v 
    --tb=short
    --alluredir=reports/allure-results
    -p no:randomly # 这行禁用pytest-randomly插件
    
testpaths = testcases
markers = 
     smoke: 冒烟测试
     regression: 回归测试
     api: API测试
     p0: 最高优先级测试用例
  p1: 高优先级测试用例
    dev: 开发环境测试用例
     uat: UAT环境测试用例 
    run: 标记测试用例的执行顺序
     smoke: 标记冒烟测试用例
     regression: 标记回归测试用例
     order: 标记测试用例的执行顺序
# Ignore warnings
filterwarnings =
    ignore::pytest.PytestAssertRewriteWarning
    ignore::DeprecationWarning
    ignore::UserWarning
    ignore::pytest.PytestUnknownMarkWarning
    ignore::pytest.PytestCollectionWarning
    ignore::pytest.PytestUnraisableExceptionWarning
    ignore::pytest.PytestUnhandledCoroutineWarning
    ignore::pytest.PytestUnhandledThreadExceptionWarning

# Test file naming patterns
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Environment variables
env =
    D:PYTHONPATH=.

