from setuptools import setup, find_packages

setup(
    name="erp_autoest",
    version="0.1.0",
    description="ERP System Automated Testing Framework",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(),
    install_requires=[
        "pytest>=7.4.3",
        "requests>=2.31.0",
        "allure-pytest>=2.13.2",
        "PyYAML>=6.0.1",
        "python-dotenv>=1.0.0",
        "locust>=2.20.0",
        "mysql-connector-python>=8.2.0",
        "pymysql>=1.1.0",
        "cryptography>=41.0.7",
        "pytest-xdist>=3.5.0",
        "pytest-rerunfailures>=12.0",
        "pytest-timeout>=2.2.0",
        "pytest-html>=4.1.1",
        "pytest-metadata>=3.1.0",
        "pytest-ordering>=0.6",
        "pytest-assume>=2.4.3",
        "pytest-repeat>=0.9.1",
        "pytest-randomly>=3.15.0",
        "pytest-sugar>=0.9.7",
        "pytest-xdist>=3.5.0",
        "pytest-rerunfailures>=12.0",
        "pytest-timeout>=2.2.0",
        "pytest-html>=4.1.1",
        "pytest-metadata>=3.1.0",
        "pytest-ordering>=0.6",
        "pytest-assume>=2.4.3",
        "pytest-repeat>=0.9.1",
        "pytest-randomly>=3.15.0",
        "pytest-sugar>=0.9.7",
        "pytest-xdist>=3.5.0",
        "pytest-rerunfailures>=12.0",
        "pytest-timeout>=2.2.0",
        "pytest-html>=4.1.1",
        "pytest-metadata>=3.1.0",
        "pytest-ordering>=0.6",
        "pytest-assume>=2.4.3",
        "pytest-repeat>=0.9.1",
        "pytest-randomly>=3.15.0",
        "pytest-sugar>=0.9.7"
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Software Development :: Testing",
    ],
    entry_points={
        "console_scripts": [
            "erp-test=testcases.main:main",
        ],
    },
) 