# 测试环境配置
erp_env: "test"
erp_version: "0630"
trantor_version: "3.0.2506"

# 基础配置_hyr
portal_url: "https://t-erp-portal-test.app.terminus.io"
iam_url: "https://t-erp-iam-test.app.terminus.io"

# header
iam_referer: "https://t-erp-iam-test.app.terminus.io/TERP_PORTAL-TERP-tpf_umwrhzbg/login"
portal_referer: "https://t-erp-portal-test.app.terminus.io/TERP_PORTAL-TERP/TERP_PORTAL/TERP_PORTAL$4f94e448-6fcd-497b-8357-66a90c82a3f9/page"

# 认证配置
tenants:
  terp:
    name: "terp"
    auth:
      username: ${TEST_AUTH_USERNAME}
      password: ${TEST_AUTH_PASSWORD}

# 数据库配置
database:
  erp_db:
    host: ${TEST_DB_HOST}
    port: ${TEST_DB_PORT}
    user: ${TEST_DB_USER}
    password: ${TEST_DB_PASSWORD}
    database: ${TEST_DB_NAME}
    charset: utf8mb4