# -*- coding: utf-8 -*-
"""Generated by api_record/recorder.py（场景骨架对齐 .cursor/rules/testcase_temp.mdc）。"""

import copy
import json
from pathlib import Path

import allure
import pytest

from testcases.comm.base_test import BaseTest
from testcases.erp_fin import FinBaseTest
from testcases.gen_md import GenMdBaseTest
from utils.report_util import a, case_decorator


# 本目录为 api_record/（非仓库根目录），仅用于定位 testdata/recorded 等录制资产
API_RECORD_ROOT = Path(__file__).resolve().parents[1]


class RecordedFlowMixin:
    @classmethod
    def _register_direct_api(cls, api_path, method, body_template=None):
        if getattr(cls, "apis", None) is None:
            cls.apis = {}
        if getattr(cls, "api_params", None) is None:
            cls.api_params = {}

        cls.apis[api_path] = {"path": api_path, "method": method}
        if method in {"POST", "PUT", "PATCH"}:
            cls.api_params[api_path] = copy.deepcopy(body_template) if body_template is not None else {}
        else:
            cls.api_params.setdefault(api_path, {})

    def _replay_recorded_api(self, api_path, method, request_body, query_params=None):
        """与 test_business_partner_management._execute_direct_api 对齐的录制回放入口。"""
        method = (method or "POST").upper()
        if method in {"GET", "DELETE"}:
            self._register_direct_api(api_path, method, body_template=request_body)
            return self.standard_api_call(
                api_key=api_path,
                set_dict=request_body,
                use_param_util=False,
                method=method,
                query_params=query_params,
            )

        inner = None
        if isinstance(request_body, dict):
            params_obj = request_body.get("params")
            if isinstance(params_obj, dict) and "request" in params_obj:
                inner = params_obj.get("request")

        if inner is not None:
            self._register_direct_api(api_path, method, body_template=request_body)
            return self.standard_api_call(
                api_key=api_path,
                set_dict=inner,
                use_param_util=False,
                param_path=["params", "request"],
                method=method,
                query_params=query_params,
            )

        self._register_direct_api(api_path, method, body_template=request_body)
        return self.standard_api_call(
            api_key=api_path,
            set_dict=request_body,
            use_param_util=False,
            param_path=[],
            method=method,
            query_params=query_params,
        )

    @staticmethod
    def _split_recorded_payload(set_dict):
        if isinstance(set_dict, dict):
            query_params = copy.deepcopy(set_dict.get("__recorded_query_params__", {}))
            body_payload = copy.deepcopy(set_dict.get("__recorded_body__", {}))
            if "__recorded_query_params__" in set_dict or "__recorded_body__" in set_dict:
                return query_params or None, body_payload
        return None, copy.deepcopy(set_dict)

@allure.epic('场景录制')
@allure.feature('Mitmproxy 页面链路')
class TestRecordedScene_1774800839(RecordedFlowMixin, GenMdBaseTest):
    """Mitmproxy 录制场景（第一版），类骨架对齐 .cursor/rules/testcase_temp.mdc。"""

    @classmethod
    def setup_class(cls):
        """安全初始化 init_data / md_cache_data（与 testcase_temp 一致）。"""
        super().setup_class()
        cls.logger.info("录制场景测试类初始化完成")
        if cls.init_data:
            cls.curr_id = cls.init_data["currency_info"][0]["curr_id"] if cls.init_data.get("currency_info") else None
            cls.coun_id = cls.init_data["country_info"][0]["coun_id"] if cls.init_data.get("country_info") else None
            cls.addr_id = cls.init_data["addr_info"][0]["id"] if cls.init_data.get("addr_info") else None
            cls.bank_id = cls.init_data["bank_info"][0]["bank_id"] if cls.init_data.get("bank_info") else None
            cls.gen_wc_head_id = cls.init_data["gen_wc_head_info"][0]["gen_wc_head_id"] if cls.init_data.get("gen_wc_head_info") else None
            cls.calender_id = cls.init_data["calender_info"][0]["id"] if cls.init_data.get("calender_info") else None
        else:
            cls.curr_id = cls.coun_id = cls.addr_id = None
            cls.bank_id = cls.gen_wc_head_id = cls.calender_id = None
        if getattr(cls, "md_cache_data", None):
            cust_info = cls.md_cache_data.get("partner_info", {}).get("cust_info", [])
            cls.cust_id = cust_info[0].get("id") if cust_info else None
            gr_come_org_info = cls.md_cache_data.get("org_info", {}).get("gr_come_org_info", [])
            cls.com_org_id = gr_come_org_info[0].get("id") if gr_come_org_info else None
            sls_org_info = cls.md_cache_data.get("org_info", {}).get("sls_org_info", [])
            cls.sls_org_id = sls_org_info[0].get("id") if sls_org_info else None
            inv_org_info = cls.md_cache_data.get("org_info", {}).get("inv_org_info", [])
            cls.inv_org_id = inv_org_info[0].get("id") if inv_org_info else None
            cls.org_business_type_ids = cls.md_cache_data.get("org_info", {}).get("org_biz_type_cf", [])
            sls_dc_md = cls.md_cache_data.get("org_info", {}).get("sls_dc_md", [])
            cls.sls_dc_id = sls_dc_md[0].get("id") if sls_dc_md else None
            inv_wh_md = cls.md_cache_data.get("org_info", {}).get("inv_wh_md", [])
            cls.wh_id = inv_wh_md[0].get("id") if inv_wh_md else None
            mat_md = cls.md_cache_data.get("mat_info", {}).get("mat_md", {})
            finp_list = mat_md.get("FINP", [])
            cls.mat_id = finp_list[0].get("id") if finp_list else None
        else:
            cls.cust_id = cls.com_org_id = cls.sls_org_id = cls.inv_org_id = None
            cls.org_business_type_ids = []
            cls.sls_dc_id = cls.wh_id = cls.mat_id = None

    @classmethod
    def teardown_class(cls):
        """转正后按业务逐表清理（禁止 for 循环表名）；录制阶段默认不删数据。"""
        try:
            cls.logger.info("录制场景 teardown_class：跳过库表清理")
        except Exception as e:
            cls.logger.error("teardown_class 失败: %s", str(e))

    @case_decorator(
        story='页面场景录制',
        title='步骤001 (sys_common_api_async_task_task_instance_count_get)',
        description='录制回放第 1 步（未映射 YAML 路径名）',
        severity="normal",
        file_level_order=1,
        tags=['录制场景', 'mitmproxy', 'sys_common'],
    )
    def test_post_sys_common_api_async_task_task_instance_count_get_001(self):
        """录制步骤 1（禁止调用其他 test_*；转正时抽 helper）。"""
        try:
            # 1. 准备 / 加载请求体
            set_dict = {
              "serviceKey": "sys_common$API_ASYNC_TASK_TASK_INSTANCE_COUNT_GET",
              "__recorded_query_params__": {},
              "__recorded_body__": {
                "serviceKey": "sys_common$API_ASYNC_TASK_TASK_INSTANCE_COUNT_GET"
              }
            }
            # 2. 拆分 query 与 body（见 RecordedFlowMixin._split_recorded_payload）
            query_params, request_body = self._split_recorded_payload(set_dict)
            # 3. 调用接口；转正后优先 standard_api_call(api_key=YAML服务名, …)
            response, _ = self._replay_recorded_api(
                api_path='/api/trantor/service/engine/execute/sys_common$API_ASYNC_TASK_TASK_INSTANCE_COUNT_GET',
                method='POST',
                request_body=request_body,
                query_params=query_params,
            )
            # 4. 断言（分页/列表类可按需改为更强的业务校验）
            self.assert_util.assert_response_success(response)
            a.json(set_dict, "录制请求体")
            a.json(response, "响应数据")
        except Exception as e:
            a.text(str(e), "失败原因")
            raise

    @case_decorator(
        story='页面场景录制',
        title='步骤002 异步任务-任务实例-查询今日任务状态(/api/async-task/task-instance/latest#GET)',
        description='录制回放第 2 步；YAML 服务名: 异步任务-任务实例-查询今日任务状态(/api/async-task/task-instance/latest#GET)',
        severity="normal",
        file_level_order=2,
        tags=['录制场景', 'mitmproxy', '接口已映射', 'sys_common'],
    )
    def test_post_异步任务_任务实例_查询今日任务状态_api_async_task_task_instance_latest_GET_002(self):
        """录制步骤 2（禁止调用其他 test_*；转正时抽 helper）。"""
        try:
            # 1. 准备 / 加载请求体
            set_dict = {
              "serviceKey": "TERP_MIGRATE$API_ASYNC_TASK_TASK_INSTANCE_LATEST_GET",
              "params": {
                "appId": 0,
                "teamId": 0
              },
              "__recorded_query_params__": {},
              "__recorded_body__": {
                "serviceKey": "TERP_MIGRATE$API_ASYNC_TASK_TASK_INSTANCE_LATEST_GET",
                "params": {
                  "appId": 0,
                  "teamId": 0
                }
              }
            }
            # 2. 拆分 query 与 body（见 RecordedFlowMixin._split_recorded_payload）
            query_params, request_body = self._split_recorded_payload(set_dict)
            # 3. 调用接口；转正后优先 standard_api_call(api_key=YAML服务名, …)
            response, _ = self._replay_recorded_api(
                api_path='/api/trantor/service/engine/execute/sys_common$API_ASYNC_TASK_TASK_INSTANCE_LATEST_GET',
                method='POST',
                request_body=request_body,
                query_params=query_params,
            )
            # 4. 断言（分页/列表类可按需改为更强的业务校验）
            self.assert_util.assert_response_success(response)
            a.json(set_dict, "录制请求体")
            a.json(response, "响应数据")
        except Exception as e:
            a.text(str(e), "失败原因")
            raise

    @case_decorator(
        story='页面场景录制',
        title='步骤003 审批流-流程任务实例-统计待办数量(/api/trantor/workflow/v2/task-instance/count#GET)',
        description='录制回放第 3 步；YAML 服务名: 审批流-流程任务实例-统计待办数量(/api/trantor/workflow/v2/task-instance/count#GET)',
        severity="normal",
        file_level_order=3,
        tags=['录制场景', 'mitmproxy', '接口已映射', 'sys_common'],
    )
    def test_post_审批流_流程任务实例_统计待办数量_api_trantor_workflow_v2_task_instance_count_GET_003(self):
        """录制步骤 3（禁止调用其他 test_*；转正时抽 helper）。"""
        try:
            # 1. 准备 / 加载请求体
            set_dict = {
              "serviceKey": "ERP_GEN$API_TRANTOR_WORKFLOW_V2_TASK_INSTANCE_COUNT_GET",
              "params": {
                "params": {
                  "appId": 0,
                  "teamId": 0
                },
                "teamId": 0
              },
              "__recorded_query_params__": {},
              "__recorded_body__": {
                "serviceKey": "ERP_GEN$API_TRANTOR_WORKFLOW_V2_TASK_INSTANCE_COUNT_GET",
                "params": {
                  "params": {
                    "appId": 0,
                    "teamId": 0
                  },
                  "teamId": 0
                }
              }
            }
            # 2. 拆分 query 与 body（见 RecordedFlowMixin._split_recorded_payload）
            query_params, request_body = self._split_recorded_payload(set_dict)
            # 3. 调用接口；转正后优先 standard_api_call(api_key=YAML服务名, …)
            response, _ = self._replay_recorded_api(
                api_path='/api/trantor/service/engine/execute/sys_common$API_TRANTOR_WORKFLOW_V2_TASK_INSTANCE_COUNT_GET',
                method='POST',
                request_body=request_body,
                query_params=query_params,
            )
            # 4. 断言（分页/列表类可按需改为更强的业务校验）
            self.assert_util.assert_response_success(response)
            a.json(set_dict, "录制请求体")
            a.json(response, "响应数据")
        except Exception as e:
            a.text(str(e), "失败原因")
            raise

    @case_decorator(
        story='页面场景录制',
        title='步骤004 GEN-合作伙伴-查询分页服务',
        description='录制回放第 4 步；YAML 服务名: GEN-合作伙伴-查询分页服务',
        severity="normal",
        file_level_order=4,
        tags=['录制场景', 'mitmproxy', '接口已映射', 'GEN_MD'],
    )
    def test_post_GEN_合作伙伴_查询分页服务_004(self):
        """录制步骤 4（禁止调用其他 test_*；转正时抽 helper）。"""
        try:
            # 1. 准备 / 加载请求体
            with open(API_RECORD_ROOT / 'testdata/recorded/gen_md_gen_business_partner_md_query_page_action_service_1774800839_004.json', "r", encoding="utf-8") as file_obj:
                set_dict = json.load(file_obj)
            # 2. 拆分 query 与 body（见 RecordedFlowMixin._split_recorded_payload）
            query_params, request_body = self._split_recorded_payload(set_dict)
            # 3. 调用接口；转正后优先 standard_api_call(api_key=YAML服务名, …)
            response, _ = self._replay_recorded_api(
                api_path='/api/trantor/service/engine/execute/GEN_MD$GEN_BUSINESS_PARTNER_MD_QUERY_PAGE_ACTION_SERVICE',
                method='POST',
                request_body=request_body,
                query_params=query_params,
            )
            # 4. 断言（分页/列表类可按需改为更强的业务校验）
            self.assert_util.assert_response_data(response)
            a.json(set_dict, "录制请求体")
            a.json(response, "响应数据")
        except Exception as e:
            a.text(str(e), "失败原因")
            raise

    @case_decorator(
        story='页面场景录制',
        title='步骤005 GEN-合作伙伴-启用服务',
        description='录制回放第 5 步；YAML 服务名: GEN-合作伙伴-启用服务',
        severity="normal",
        file_level_order=5,
        tags=['录制场景', 'mitmproxy', '接口已映射', 'GEN_MD'],
    )
    def test_post_GEN_合作伙伴_启用服务_005(self):
        """录制步骤 5（禁止调用其他 test_*；转正时抽 helper）。"""
        try:
            # 1. 准备 / 加载请求体
            with open(API_RECORD_ROOT / 'testdata/recorded/gen_md_gen_business_partner_md_enabled_action_service_1774800839_005.json', "r", encoding="utf-8") as file_obj:
                set_dict = json.load(file_obj)
            # 2. 拆分 query 与 body（见 RecordedFlowMixin._split_recorded_payload）
            query_params, request_body = self._split_recorded_payload(set_dict)
            # 3. 调用接口；转正后优先 standard_api_call(api_key=YAML服务名, …)
            response, _ = self._replay_recorded_api(
                api_path='/api/trantor/service/engine/execute/GEN_MD$GEN_BUSINESS_PARTNER_MD_ENABLED_ACTION_SERVICE',
                method='POST',
                request_body=request_body,
                query_params=query_params,
            )
            # 4. 断言（分页/列表类可按需改为更强的业务校验）
            self.assert_util.assert_response_success(response)
            a.json(set_dict, "录制请求体")
            a.json(response, "响应数据")
        except Exception as e:
            a.text(str(e), "失败原因")
            raise

    @case_decorator(
        story='页面场景录制',
        title='步骤006 GEN-合作伙伴-查询分页服务',
        description='录制回放第 6 步；YAML 服务名: GEN-合作伙伴-查询分页服务',
        severity="normal",
        file_level_order=6,
        tags=['录制场景', 'mitmproxy', '接口已映射', 'GEN_MD'],
    )
    def test_post_GEN_合作伙伴_查询分页服务_006(self):
        """录制步骤 6（禁止调用其他 test_*；转正时抽 helper）。"""
        try:
            # 1. 准备 / 加载请求体
            with open(API_RECORD_ROOT / 'testdata/recorded/gen_md_gen_business_partner_md_query_page_action_service_1774800839_006.json', "r", encoding="utf-8") as file_obj:
                set_dict = json.load(file_obj)
            # 2. 拆分 query 与 body（见 RecordedFlowMixin._split_recorded_payload）
            query_params, request_body = self._split_recorded_payload(set_dict)
            # 3. 调用接口；转正后优先 standard_api_call(api_key=YAML服务名, …)
            response, _ = self._replay_recorded_api(
                api_path='/api/trantor/service/engine/execute/GEN_MD$GEN_BUSINESS_PARTNER_MD_QUERY_PAGE_ACTION_SERVICE',
                method='POST',
                request_body=request_body,
                query_params=query_params,
            )
            # 4. 断言（分页/列表类可按需改为更强的业务校验）
            self.assert_util.assert_response_data(response)
            a.json(set_dict, "录制请求体")
            a.json(response, "响应数据")
        except Exception as e:
            a.text(str(e), "失败原因")
            raise

    @case_decorator(
        story='页面场景录制',
        title='步骤007 GEN-合作伙伴-禁用服务',
        description='录制回放第 7 步；YAML 服务名: GEN-合作伙伴-禁用服务',
        severity="normal",
        file_level_order=7,
        tags=['录制场景', 'mitmproxy', '接口已映射', 'GEN_MD'],
    )
    def test_post_GEN_合作伙伴_禁用服务_007(self):
        """录制步骤 7（禁止调用其他 test_*；转正时抽 helper）。"""
        try:
            # 1. 准备 / 加载请求体
            with open(API_RECORD_ROOT / 'testdata/recorded/gen_md_gen_business_partner_md_disabled_action_service_1774800839_007.json', "r", encoding="utf-8") as file_obj:
                set_dict = json.load(file_obj)
            # 2. 拆分 query 与 body（见 RecordedFlowMixin._split_recorded_payload）
            query_params, request_body = self._split_recorded_payload(set_dict)
            # 3. 调用接口；转正后优先 standard_api_call(api_key=YAML服务名, …)
            response, _ = self._replay_recorded_api(
                api_path='/api/trantor/service/engine/execute/GEN_MD$GEN_BUSINESS_PARTNER_MD_DISABLED_ACTION_SERVICE',
                method='POST',
                request_body=request_body,
                query_params=query_params,
            )
            # 4. 断言（分页/列表类可按需改为更强的业务校验）
            self.assert_util.assert_response_success(response)
            a.json(set_dict, "录制请求体")
            a.json(response, "响应数据")
        except Exception as e:
            a.text(str(e), "失败原因")
            raise

    @case_decorator(
        story='页面场景录制',
        title='步骤008 GEN-合作伙伴-查询详情服务',
        description='录制回放第 8 步；YAML 服务名: GEN-合作伙伴-查询详情服务',
        severity="normal",
        file_level_order=8,
        tags=['录制场景', 'mitmproxy', '接口已映射', 'GEN_MD'],
    )
    def test_post_GEN_合作伙伴_查询详情服务_008(self):
        """录制步骤 8（禁止调用其他 test_*；转正时抽 helper）。"""
        try:
            # 1. 准备 / 加载请求体
            with open(API_RECORD_ROOT / 'testdata/recorded/gen_md_gen_business_partner_md_query_detail_action_service_1774800839_008.json', "r", encoding="utf-8") as file_obj:
                set_dict = json.load(file_obj)
            # 2. 拆分 query 与 body（见 RecordedFlowMixin._split_recorded_payload）
            query_params, request_body = self._split_recorded_payload(set_dict)
            # 3. 调用接口；转正后优先 standard_api_call(api_key=YAML服务名, …)
            response, _ = self._replay_recorded_api(
                api_path='/api/trantor/service/engine/execute/GEN_MD$GEN_BUSINESS_PARTNER_MD_QUERY_DETAIL_ACTION_SERVICE',
                method='POST',
                request_body=request_body,
                query_params=query_params,
            )
            # 4. 断言（分页/列表类可按需改为更强的业务校验）
            self.assert_util.assert_response_success(response)
            a.json(set_dict, "录制请求体")
            a.json(response, "响应数据")
        except Exception as e:
            a.text(str(e), "失败原因")
            raise

    @case_decorator(
        story='页面场景录制',
        title='步骤009 GEN-合作伙伴-查询详情服务',
        description='录制回放第 9 步；YAML 服务名: GEN-合作伙伴-查询详情服务',
        severity="normal",
        file_level_order=9,
        tags=['录制场景', 'mitmproxy', '接口已映射', 'GEN_MD'],
    )
    def test_post_GEN_合作伙伴_查询详情服务_009(self):
        """录制步骤 9（禁止调用其他 test_*；转正时抽 helper）。"""
        try:
            # 1. 准备 / 加载请求体
            with open(API_RECORD_ROOT / 'testdata/recorded/gen_md_gen_business_partner_md_query_detail_action_service_1774800839_009.json', "r", encoding="utf-8") as file_obj:
                set_dict = json.load(file_obj)
            # 2. 拆分 query 与 body（见 RecordedFlowMixin._split_recorded_payload）
            query_params, request_body = self._split_recorded_payload(set_dict)
            # 3. 调用接口；转正后优先 standard_api_call(api_key=YAML服务名, …)
            response, _ = self._replay_recorded_api(
                api_path='/api/trantor/service/engine/execute/GEN_MD$GEN_BUSINESS_PARTNER_MD_QUERY_DETAIL_ACTION_SERVICE',
                method='POST',
                request_body=request_body,
                query_params=query_params,
            )
            # 4. 断言（分页/列表类可按需改为更强的业务校验）
            self.assert_util.assert_response_success(response)
            a.json(set_dict, "录制请求体")
            a.json(response, "响应数据")
        except Exception as e:
            a.text(str(e), "失败原因")
            raise

    @case_decorator(
        story='页面场景录制',
        title='步骤010 (系统)反向构建树以及同步查询出所有同级服务',
        description='录制回放第 10 步；YAML 服务名: (系统)反向构建树以及同步查询出所有同级服务',
        severity="normal",
        file_level_order=10,
        tags=['录制场景', 'mitmproxy', '接口已映射', 'GEN_MD'],
    )
    def test_post_系统_反向构建树以及同步查询出所有同级服务_010(self):
        """录制步骤 10（禁止调用其他 test_*；转正时抽 helper）。"""
        try:
            # 1. 准备 / 加载请求体
            with open(API_RECORD_ROOT / 'testdata/recorded/gen_md_sys_reverseconstructtreeservice_1774800839_010.json', "r", encoding="utf-8") as file_obj:
                set_dict = json.load(file_obj)
            # 2. 拆分 query 与 body（见 RecordedFlowMixin._split_recorded_payload）
            query_params, request_body = self._split_recorded_payload(set_dict)
            # 3. 调用接口；转正后优先 standard_api_call(api_key=YAML服务名, …)
            response, _ = self._replay_recorded_api(
                api_path='/api/trantor/service/engine/execute/GEN_MD$SYS_ReverseConstructTreeService',
                method='POST',
                request_body=request_body,
                query_params=query_params,
            )
            # 4. 断言（分页/列表类可按需改为更强的业务校验）
            self.assert_util.assert_response_success(response)
            a.json(set_dict, "录制请求体")
            a.json(response, "响应数据")
        except Exception as e:
            a.text(str(e), "失败原因")
            raise

    @case_decorator(
        story='页面场景录制',
        title='步骤011 GEN-合作伙伴-保存服务',
        description='录制回放第 11 步；YAML 服务名: GEN-合作伙伴-保存服务',
        severity="normal",
        file_level_order=11,
        tags=['录制场景', 'mitmproxy', '接口已映射', 'GEN_MD'],
    )
    def test_post_GEN_合作伙伴_保存服务_011(self):
        """录制步骤 11（禁止调用其他 test_*；转正时抽 helper）。"""
        try:
            # 1. 准备 / 加载请求体
            with open(API_RECORD_ROOT / 'testdata/recorded/gen_md_gen_business_partner_md_save_action_service_1774800839_011.json', "r", encoding="utf-8") as file_obj:
                set_dict = json.load(file_obj)
            # 2. 拆分 query 与 body（见 RecordedFlowMixin._split_recorded_payload）
            query_params, request_body = self._split_recorded_payload(set_dict)
            # 3. 调用接口；转正后优先 standard_api_call(api_key=YAML服务名, …)
            response, _ = self._replay_recorded_api(
                api_path='/api/trantor/service/engine/execute/GEN_MD$GEN_BUSINESS_PARTNER_MD_SAVE_ACTION_SERVICE',
                method='POST',
                request_body=request_body,
                query_params=query_params,
            )
            # 4. 断言（分页/列表类可按需改为更强的业务校验）
            self.assert_util.assert_response_success(response)
            a.json(set_dict, "录制请求体")
            a.json(response, "响应数据")
        except Exception as e:
            a.text(str(e), "失败原因")
            raise

    @case_decorator(
        story='页面场景录制',
        title='步骤012 导入导出配置管理接口-查询表头选择记录(/api/gei/task/config/queryHeaderSelectiveRecord#POST)',
        description='录制回放第 12 步；YAML 服务名: 导入导出配置管理接口-查询表头选择记录(/api/gei/task/config/queryHeaderSelectiveRecord#POST)',
        severity="normal",
        file_level_order=12,
        tags=['录制场景', 'mitmproxy', '接口已映射', 'sys_common'],
    )
    def test_post_导入导出配置管理接口_查询表头选择记录_api_gei_task_config_queryHeaderSelectiveRecord_POST_012(self):
        """录制步骤 12（禁止调用其他 test_*；转正时抽 helper）。"""
        try:
            # 1. 准备 / 加载请求体
            with open(API_RECORD_ROOT / 'testdata/recorded/sys_common_api_gei_task_config_query_header_selective_record_post_1774800839_012.json', "r", encoding="utf-8") as file_obj:
                set_dict = json.load(file_obj)
            # 2. 拆分 query 与 body（见 RecordedFlowMixin._split_recorded_payload）
            query_params, request_body = self._split_recorded_payload(set_dict)
            # 3. 调用接口；转正后优先 standard_api_call(api_key=YAML服务名, …)
            response, _ = self._replay_recorded_api(
                api_path='/api/trantor/service/engine/execute/sys_common$API_GEI_TASK_CONFIG_QUERY_HEADER_SELECTIVE_RECORD_POST',
                method='POST',
                request_body=request_body,
                query_params=query_params,
            )
            # 4. 断言（分页/列表类可按需改为更强的业务校验）
            self.assert_util.assert_response_success(response)
            a.json(set_dict, "录制请求体")
            a.json(response, "响应数据")
        except Exception as e:
            a.text(str(e), "失败原因")
            raise
